services:
  #(customize the service name in the network)
  mysql:
    image: mysql:8.0
    #(Customize the display name)
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: thumb_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    #(host:container)
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7.0
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: password
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
