spring:
  application:
    name: SocialLikeBackend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thumb_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: password
knife4j:
  enable: true
  setting:
    language: en
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl